/* Default split names for the game. TODO: This needs to be customizable. */

DROP TABLE IF EXISTS cfg_default_split_names;
CREATE TABLE cfg_default_split_names(split_index INTEGER, split_name TEXT);

INSERT INTO cfg_default_split_names(split_index, split_name)
VALUES
	(1, '-Start'),
	(2, '-Village'),
	(3, '-Farm'),
	(4, '{1-1} Boulder'),
	(5, '-Canyon'),
	(6, '-Factory'),
	(7, '{1-2} Enter House'),
	(8, '-Exit House'),
	(9, '-Village 2'),
	(10, '-Underground'),
	(11, '-Graveyard'),
	(12, '-Crows'),
	(13, '-Swamp'),
	(14, '{1-3} Del Lago'),
	(15, '-Wake Up'),
	(16, '-Waterfall'),
	(17, '-Boat Ride'),
	(18, '-El Gigante'),
	(19, '-Dogs'),
	(20, '{2-1} Church'),
	(21, '-Ashley'),
	(22, '-Graveyard 2'),
	(23, '-Underground 2'),
	(24, '-Village 3'),
	(25, '-Farm 2'),
	(26, '{2-2} Cabin'),
	(27, '-Lever'),
	(28, '-El Gigante 2'),
	(29, '-Gondola'),
	(30, '-Mendez'),
	(31, '-Gondola 2'),
	(32, '{2-3} Truck'),
	(33, '-Enter Castle'),
	(34, '-Catapults'),
	(35, '-Swords Room'),
	(36, '-Castle Key'),
	(37, '-Garrador'),
	(38, '-Water Hall'),
	(39, '{3-1} Ceremony Room'),
	(40, '-Ceremony Room'),
	(41, '-Novistadors 1'),
	(42, '-Ceremony Room 2'),
	(43, '-Gallery'),
	(44, '-Fountain'),
	(45, '{3-2} Maze'),
	(46, '-Bedroom'),
	(47, '-Cage'),
	(48, '{3-3} Bridge'),
	(49, '-Save Ashley'),
	(50, '-Cranks'),
	(51, '-Puzzle'),
	(52, '{3-4} Exit'),
	(53, '-Reunited'),
	(54, '-Cart Room'),
	(55, '-Lava Room'),
	(56, '-Cart Room 2'),
	(57, '-Chimera Wall'),
	(58, '-Cart Room 3'),
	(59, '-Hallway'),
	(60, '-Queen''s Grail'),
	(61, '-Hallway 2'),
	(62, '-King''s Grail'),
	(63, '-Hallway 3'),
	(64, '-Novistadors 2'),
	(65, '-Catapults 2'),
	(66, '-Clock Tower'),
	(67, '-Bridge'),
	(68, '-Garradors'),
	(69, '-Striker'),
	(70, '{4-1} Verdugo'),
	(71, '-Merchant'),
	(72, '-Boulder'),
	(73, '-El Gigantes'),
	(74, '{4-2} Novistadors 3'),
	(75, '-Ruins'),
	(76, '-Enter Mines'),
	(77, '-Minecart'),
	(78, '{4-3} Emblem'),
	(79, '-Salazar Statue'),
	(80, '-Elevator'),
	(81, '-Salazar'),
	(82, '{4-4} Exit'),
	(83, '-Enter Island'),
	(84, '-Outside Facility'),
	(85, '-Oven Man'),
	(86, '-Monitor Room'),
	(87, '-Garage Door'),
	(88, '-Hallway 4'),
	(89, '-Regenerator'),
	(90, '-Hallway 5'),
	(91, '-Freezer'),
	(92, '-Hallway 6'),
	(93, '-Trash Room'),
	(94, '-Cell'),
	(95, '-Stairs Room'),
	(96, '-Iron Maiden'),
	(97, '-Stairs Room 2'),
	(98, '{5-1} Cell'),
	(99, '-Ashley''s Back'),
	(100, '-Observation Room'),
	(101, '-Iron Maidens'),
	(102, '-Wrecking Ball'),
	(103, '-Regenerators'),
	(104, '-Truck'),
	(105, '{5-2} Merchant'),
	(106, '-Ceremony Room 3'),
	(107, '-Krauser'),
	(108, '-Lasers'),
	(109, '-Cave'),
	(110, '-U-3'),
	(111, '-Tents'),
	(112, '{5-3} Krauser'),
	(113, '-Military Area'),
	(114, '-RIP Mike'),
	(115, '-Ruins 2'),
	(116, '-Jail'),
	(117, '-Key Card'),
	(118, '-Ashley Again'),
	(119, '{5-4} Plaga Removal'),
	(120, '-Exit'),
	(121, '-Construction Site'),
	(122, '-Saddler'),
	(123, '{End} Jetski');


DROP TABLE IF EXISTS cfg_chapter_area_splits_from_to;
CREATE TABLE cfg_chapter_area_splits_from_to(from_split_index INTEGER, to_split_index INTEGER, chapter TEXT, area TEXT);

INSERT INTO cfg_chapter_area_splits_from_to(from_split_index, to_split_index, chapter, area)
VALUES
    (1, 4, '1-1', 'Village'),
    (5, 7, '1-2', 'Village'),
    (8, 14, '1-3', 'Village'),
    (15, 20, '2-1', 'Village'),
    (21, 26, '2-2', 'Village'),
    (27, 32, '2-3', 'Village'),
    (33, 39, '3-1', 'Castle'),
    (40, 45, '3-2', 'Castle'),
    (46, 48, '3-3', 'Castle'),
    (49, 52, '3-4', 'Castle'),
    (53, 70, '4-1', 'Castle'),
    (71, 74, '4-2', 'Castle'),
    (75, 78, '4-3', 'Castle'),
    (79, 82, '4-4', 'Castle'),
    (83, 98, '5-1', 'Island'),
    (99, 105, '5-2', 'Island'),
    (106, 112, '5-3', 'Island'),
    (113, 119, '5-4', 'Island'),
    (120, 123, '6-1', 'Island');


DROP TABLE IF EXISTS cfg_splits_per_area;
CREATE TABLE cfg_splits_per_area(sort INTEGER, number_of_splits INTEGER, area TEXT);

INSERT INTO cfg_splits_per_area(sort, number_of_splits, area)
VALUES
	(1, 32, 'Village'),
	(2, 50, 'Castle'),
	(3, 41, 'Island');


/* RNG names for each pattern. TODO: This needs to be customizable. */

DROP TABLE IF EXISTS cfg_rng;
CREATE TABLE cfg_rng(pattern TEXT);

INSERT INTO cfg_rng(pattern)
VALUES
	('1-a No dive'),
	('1-b Late dive'),
	('1-c Early dive'),
	('2-a Fast Mendez'),
	('2-b Medium Mendez'),
	('2-c Slow Mendez'),
	('3-a Perfect catapult'),
	('3-b Stagger catapult'),
	('3-c Boulder catapult'),
	('4-a Great cabin'),
	('4-b Good cabin'),
	('4-c Average cabin'),
	('4-d Bad cabin'),
	('4-e Terrible cabin'),
	('5-a Great water hall'),
	('5-b Good water hall'),
	('5-c Average water hall'),
	('5-d Bad water hall'),
	('5-e Terrible water hall'),
	('6-a Great novis 1'),
	('6-b Good novis 1'),
	('6-c Average novis 1'),
	('6-d Bad novis 1'),
	('6-e Terrible novis 1'),
	('7-a Great gallery'),
	('7-b Good gallery'),
	('7-c Average gallery'),
	('7-d Bad gallery'),
	('7-e Terrible gallery'),
	('8-a Great novis 2'),
	('8-b Good novis 2'),
	('8-c Average novis 2'),
	('8-d Bad novis 2'),
	('8-e Terrible novis 2'),
	('9-a Great novis 3'),
	('9-b Good novis 3'),
	('9-c Average novis 3'),
	('9-d Bad novis 3'),
	('9-e Terrible novis 3'),
	('90-a Great u3'),
	('90-b Good u3'),
	('90-c Average u3'),
	('90-d Bad u3'),
	('90-e Terrible u3'),
	('91-a Great Krauser'),
	('91-b Good Krauser'),
	('91-c Average Krauser'),
	('91-d Bad Krauser'),
	('91-e Terrible Krauser'),
	('92-a Great war room'),
	('92-b Good war room'),
	('92-c Average war room'),
	('92-d Bad war room'),
	('92-e Terrible war room'),
	('93-a Great key card'),
	('93-b Good key card'),
	('93-c Average key card'),
	('93-d Bad key card'),
	('93-e Terrible key card');


/* All the dates between 2020 and 2030. */

DROP TABLE IF EXISTS cfg_dates;
CREATE TABLE cfg_dates AS
SELECT(generate_series(DATE '2020-01-01', DATE '2030-12-31', INTERVAL '1 day'))::date AS date;