[project]
name = "livesplit-analytics-database"
version = "0.2.0"
description = "Ingests LiveSplit files (.lss) to create a local SQL database with all sorts of useful analytics about them. Can be integrated with the Google Drive and Google Sheets API to make it automated."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "basedpyright>=1.39.10",
    "defusedxml>=0.7.1",
    "gspread>=6.2.1",
    "openpyxl>=3.1.5",
    "pandas>=2.3.0",
    "psycopg[binary]>=3.2.9",
    "pydrive2>=1.21.3",
    "pyyaml>=6.0.2",
    "ruff>=0.16.4",
]
