[project]
name = "livesplit-analytics-database"
version = "0.2.0"
description = "Ingests LiveSplit files (.lss) to create a local SQL database with all sorts of useful analytics about them. Can be integrated with the Google Drive and Google Sheets API to make it automated."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "basedpyright>=1.39.10",
    "defusedxml>=0.7.1",
    "gspread>=6.2.1",
    "loguru>=0.7.3",
    "openpyxl>=3.1.5",
    "pandas-stubs>=3.0.5.260730",
    "polars>=1.44.2",
    "psycopg[binary]>=3.2.9",
    "pydantic>=2.13.5",
    "pydrive2>=1.21.3",
    "pyyaml>=6.0.2",
    "ruff>=0.16.4",
    "xlsxwriter>=3.2.9",
]
